version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    env_file:
      - .env
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - backend

  bff:
    build: hamza3991/bffapp
    ports:
      - "8083:80"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - backend
  
  front:
    build: hamza3991/frontapp
    ports:
      - "8080:80"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - backend

networks:
  backend:
