# Utilisation de l'image nginx
FROM nginx:latest

# Copie des fichiers du répertoire front/browser dans le conteneur nginx
COPY ./browser /usr/share/nginx/html

# L'image nginx expose par défaut le port 80, pas besoin de spécifier l'instruction EXPOSE
